title: Simon Kingston 
logo: "/images/logo.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Software Engineer with expertise in Artificial Intelligence, Operational Research and Big Data Analytics. More than 
  three-year’s experience in developing data-related solutions for companies and academic institutions. Keen to deliver innovative
   structured solutions to business problems on time and utilising best practices.
  <br><br>
  
  <a href="www.linkedin.com/in/simonkingston2020">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

